//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DateOfBirth { get; set; }
        public string ParentOrGuardianFirstName { get; set; }
        public string ParentOrGuardianLastName { get; set; }
        public string ParentOrGuardianPhoneNumber { get; set; }
        public string ParentOrGuardianEmailAddress { get; set; }
        public int FormId { get; set; }
    
        public virtual Form Form { get; set; }
    }
}
